.open(env + "/user/edit/password") 
.type(#oldPassword , basicPassword)
.type(#newPassword1 , testPassword) 
.type(#newPassword2 , testPassword) 
.click(#btn)
.wait(wait) 
.open(env + "/signout") 
.type(".primary" , basicUsername)
.type(".secondary" , testPassword) 
.open(env + "/user/edit/password") 
.type(#oldPassword , testPassword) 
.type(#newPassword1 , basicPassword) 
.type(#newPassword2 , basicPassword) 
.click(#btn) 
